### ISSUE TITLE
shouldn't publish private key

### ISSUE THREAD

**Issue by shaunakg** [princebaretto99/RealTimeStockMarket#2]
i have no idea what this project is - i just followed a dependency graph here. however according to [this](https://crypto.stackexchange.com/questions/2706/what-is-the-harm-if-i-publish-an-encrypted-rsa-private-key-publicly) i don't think you should publish an RSA private key.

**Comment by princebaretto99** [comment]
That was a faulty private-key... anyways deleted it now. 
Thank You.

**Comment by princebaretto99** [comment]
That was a faulty private-key. Anyways deleted it now. 
Thank You.
